### ISSUE TITLE
implement command chaining

### ISSUE THREAD

**Issue by pefoley2** [tjcsl/cslbot#100]
e.g. !slogan !ahamilto

**Comment by creffett** [comment]
My thought:  a first step here would be to add --filter, which gets picked up by the bot before running commands and tells it to run a command's output through said filter(s).

**Comment by pefoley2** [comment]
so, !command --filter args -> run filter on !command args basically

**Comment by creffett** [comment]
Correct, and you could either make the filter a comma-separated list or support multiple --filter args, will think about that. The handler would need to use parse_known_args and hand off everything but --filter to the underlying command.

**Comment by pefoley2** [comment]
This could also use known_commands to dynamically generate a restricted set of commands to match.
