### ISSUE TITLE
Server doesn't work properly with ipv6

### ISSUE THREAD

**Issue by pefoley2** [tjcsl/cslbot#774]
Appears to be caused by ipv6 dns servers, but it's unclear how to fix this.

**Comment by csssuf** [comment]
Has this been fixed? @pefoley2

**Comment by pefoley2** [comment]
I don't know.

**Comment by creffett** [comment]
I'm running creffbot on IPv6 without issue so far, I think this can be closed until a more specific issue comes up.

**Comment by pefoley2** [comment]
Have you run ./scripts/reload, does it work?

**Comment by creffett** [comment]
Pending the fix in pullreq #936, yes it does

**Comment by pefoley2** [comment]
Ok, unless we get a more specific bug report, I'm closing this for now.
